---
title: Cultural Attire
baseurl: "/"
permalink: "/:title/"
palette: purple
header:
  title: Cultural Attire
  logo_img: "/images/cultural attire (1).png"
  has_nav: true
  menu:
    actions:
    - label: Sign Up
      url: "/signup"
footer:
  logo_img: ''
  tagline: ''
  has_nav: true
  nav_title: Cultural Attire
  has_social: true
  social_title: Community
  has_subscribe: true
  subscribe_title: Subscribe
  subscribe_content: Stay up to date with our latest news.
  content: Design & Develop by Amrit Kaur &copy; Cultural. All rights reserved.
  links:
  - text: Made with Stackbit
    url: https://www.stackbit.com
    new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
